### PR TITLE
Update SCB->VTOR to OS_NVIC_VTOR in los_hwi.c and create .gitignore

### PR DESCRIPTION
**Pull request by letfly**

### CODE REVIEW

**Comment by chaifangming** [comment]
Hi letfly,

Thanks for you help on LiteOS project.

I have a question here: why would us update "SCB->VTOR" to "OS_NVIC_VTOR"?

Thanks,

**Comment by letfly** [comment]
Cortex-m0 has no VTOR field

**Comment by letfly** [comment]
Do not you still understand it? The address about SCB->VTOR is 0xE000ED08 in CORTEX-M Series Processors, and OS_NVIC_VTOR in los_hwi.h is also 0xE000ED08.

**Comment by chaifangming** [comment]
Hi Letfly,

See my comments inline:

> 
> 
> Cortex-m0 has no VTOR field, also can say that 'SCB_Type' has no member named 'VTOR' in cortex-m0

Yes, SCB_Type do not have VTOR when building cortex-m0, and this is correct, because cortex-m0 MCUs do not have VTOR register, and this is just the reason why CMSIS header files do not define VTOR in SCB_Type for cortex-m0.

For cortex-m0+, VTOR is optinal, so CMSIS header file just define it as:

```C
#if defined (__VTOR_PRESENT) && (__VTOR_PRESENT == 1U)
  __IOM uint32_t VTOR;                   /*!< Offset: 0x008 (R/W)  Vector Table Offset Register */
#else
        uint32_t RESERVED0;
#endif
```


> 
> 
> Do not you still understand it? The address about SCB->VTOR is 0xE000ED08 in CORTEX-M Series Processors, and OS_NVIC_VTOR in los_hwi.h is also 0xE000ED08.

Yes I understand they have the same values, but it is better to use SCB which is defined in the CMSIS header files. Refer to my comments above.

Thanks you again for your help on LiteOS project. But I'm sorry I will close this PR as the update is  unnecessary :-)

Thanks,
Fangming

**Comment by chaifangming** [comment]
cortex-m0 projects should remove los_hwi.c for now. And use the legacy mode of IRQ handlers, which  is just place IRQ handlers in the IRQ handling table.

Of cause, routine table can be supported with cortex-m0 even there is no VTOR register, but that will spent more CPU circles, there is no plan to do that for now.

**Comment by letfly** [comment]
OK

**Pull request closed without merging**
